title: USI Informatics Course Summaries
description: Unofficial student-written course notes / summaries / cheat-sheets for Bachelor and Master courses in Informatics at the Universit√† della Svizzera italiana (USI), Lugano.
theme: jekyll-theme-cayman

url: "https://fabianbosshard.github.io/usi-informatics-course-summaries"
baseurl: ""            # keep empty because the site is at repo root
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap